// src/react/app.jsx
/*
 * @Date: 2020-04-11 21:42:54
 * @Author: innocces
 * @LastEditors: innocces
 * @LastEditTime: 2020-04-12 16:44:05
 * @FilePath: /eventBus/src/react/app.jsx
 * @Description: react entry
 */
import React from 'react'

import '../style/style.less'
import Icon from '../vue/component/Icon/react.index.jsx'
console.log(Icon)

function App() {
  return <div className='react-app-word'>react content<Icon>123</Icon></div>
}

export default App

// src/vue/app.vue
<!--
 * @Date: 2020-04-11 21:18:44
 * @Author: innocces
 * @LastEditors: innocces
 * @LastEditTime: 2020-04-12 18:16:44
 * @FilePath: /eventBus/src/vue/app.vue
 * @Description: app vue
 -->
<template>
  <div class='app'>
    vue content
    <Icon>
      dsjdsndsjdjshdjhsd
    </Icon>
  </div>
</template>

<script>
import Icon from './component/Icon/vue.index'
console.log(Icon)

export default {
  name: 'App',
  data() {
    return {

    }
  },
  components: {
    Icon
  }
}
</script>

<style lang="less" src='../style/style.less'></style>
