// src/component/Comment/comment.jsx
import React, {
  useState,
  useReducer,
  useCallback
} from 'react'

import './index.less'

import Icon from '../Icon/icon.jsx'
import CommentAction from './CommentAction/action.jsx'

// 使用reducer来代替eventBus
const initialState = {
  showAction: false
}


const Comment = ({
  comment = {},
  commentAction,
  children
}) => {
  function reducer(state, action) {
    switch(action.type) {
      case 'commentActionVisible': 
        return { showAction: !state.showAction }
      case 'commentAction':
        commentAction(action.payload.type)
        return state
    }
  }

  const [ state, dispatch ] = useReducer(reducer, initialState)

  return (
    <div className='comment'>
      <div className='comment-header'>
        <Icon
          name={ comment.type }
        >
          { comment.type }
        </Icon>
        <span className='comment-day'>{ comment.data }</span>
      </div>
      <div className='comment-body'>
        <p className='comment-body-words'>{ comment.content }</p>

        {
          !children
          ?
          <CommentAction 
            value={ state.showAction }
            CommentEventBus={ dispatch }
          />
          :
          <>
            { children }
          </>
        }
      </div>
    </div>
  )
}

export default Comment

// src/component/Comment/comment.vue
<!--
 * @Date: 2020-04-12 18:37:40
 * @Author: innocces
 * @LastEditors: innocces
 * @LastEditTime: 2020-04-12 22:48:33
 * @FilePath: /eventBus/src/component/Comment/comment.vue
 * @Description: comment
 -->
<template>
  <div class='comment'>
    <div class='comment-header'>
      <Icon
        :name='comment.type'
      >
        {{ comment.type }}
      </Icon>
      <span class='comment-day'>{{ comment.data }}</span>
    </div>
    <div class='comment-body'>
      <p class='comment-body-words'>{{ comment.content }}</p>

      <CommentAction 
        v-if='!$slots.action'
        v-model='showAction'
        :CommentEventBus='CommentEventBus'
      />
      <slot 
        v-else
        name='action'  
        :slotScope='comment.type'
      />
    </div>
  </div>
</template>

<script>
import props from './props'
import Icon from '../Icon/icon.vue'
import CommentAction from './CommentAction/action.vue'

import Vue from 'vue'

export default {
  props,
  name: 'Comment',
  components: {
    Icon,
    CommentAction
  },
  data() {
    return {
      CommentEventBus: null,
      showAction: false
    }
  },
  created() {
    // 创建状态bus监听事件
    const CommentEventBus = new Vue()
    this.CommentEventBus = CommentEventBus

    CommentEventBus.$on('commentAction', this.commentAction)
    CommentEventBus.$on('commentActionVisible', this.changeActionVisible)
  },
  methods: {
    commentAction(type) {
      this.$emit('action', type)
    },
    changeActionVisible() {
      this.showAction = !this.showAction
    }
  }
}
</script>

<style lang='less' src='./index.less'></style>
