// src/vue/app.vue
<!--
 * @Date: 2020-04-11 21:18:44
 * @Author: innocces
 * @LastEditors: innocces
 * @LastEditTime: 2020-04-11 22:44:09
 * @FilePath: /eventBus/src/vue/app.vue
 * @Description: app vue
 -->
<template>
  <div class='app'>vue content</div>
</template>

<script>
export default {
  name: 'App'
}
</script>

<style lang="less">
  .app {
    color: red;
  }
</style>

// src/react/app.js
/*
 * @Date: 2020-04-11 21:42:54
 * @Author: innocces
 * @LastEditors: innocces
 * @LastEditTime: 2020-04-11 21:55:34
 * @FilePath: /eventBus/src/react/app.js
 * @Description: react entry
 */
import React from 'react'

import './app.less'

function App() {
  return <div className='react-app-word'>react content</div>
}

export default App
